### ISSUE TITLE
enclave-build minifies dev version, not production

### ISSUE THREAD

**Issue by jondcallahan** [eanplatter/enclave#107]
Running `npm run enclave-build` results in a minified _dev_ version of react being included in `index_bundle.js` throwing this error 

> index_bundle.js:1 Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.

Expected behavior: the included webpack build config sets the node env to production resulting in a minified production build being included in `index_bundle.js`

**Comment by eanplatter** [comment]
Hmmm, when you run `npm run enclave-serve` is it giving you a non-minified version on `http://localhost:8080`?

**Comment by jondcallahan** [comment]
It is serving the non-minified version when running `enclave-serve`

**Comment by eanplatter** [comment]
Ah ok. I'll get on this, unless you'd like to make the PR :)

**Comment by eanplatter** [comment]
#108 Fixes this. Sorry about the delay!
