### ISSUE TITLE
Replace HMR

### ISSUE THREAD

**Issue by eanplatter** [eanplatter/enclave#11]
I think it's deprecated, but then again I'm not sure what replaced it D:

**Comment by shipstar** [comment]
Dan Abramov wrote a long blog post about the evolution of hot reloading yesterday: https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf#.hwu519u2f

The tl;dr seems to be that if you are in a pure Flux/Redux/etc. world, you can use the built-in webpack HMR code now, but if you have local state, you'll still need to use one of the hacks (react-hot-loader or the Babel react-transform). It seems like the ultimate goal is to refactor React to play nice with hot reloading.

Hope that helps!

**Comment by eanplatter** [comment]
Yeah I saw that post!

Maybe we'll keep it as is for now until something a bit more solid is around.
