### ISSUE TITLE
start script saves files two folders up?

### ISSUE THREAD

**Issue by alex-wilmer** [eanplatter/enclave#19]
I was pretty surprised by the paths enclave decided to place the application files. Why not in the current directory?

```
var clientFiles = {
  package: '../../package.json',
  config: '../../enclave.js'
}
```

The comment says `These are the paths for files that live in the user's application root.` it actually installed the files two folders above my application root.

**Comment by FiberJW** [comment]
This is odd. It worked perfectly for me. The `../..` is two folders up from `/node_modules/enclave/` if I'm correct which is why he chose those paths.

**Comment by eanplatter** [comment]
Weird, what environment are you coding on @alex-wilmer ?

**Comment by alex-wilmer** [comment]
OSX:

![screen shot 2016-03-10 at 10 05 00 am](https://cloud.githubusercontent.com/assets/2880089/13673702/49e47720-e6a8-11e5-9fe3-d3de2e442f70.png)

![screen shot 2016-03-10 at 10 08 45 am](https://cloud.githubusercontent.com/assets/2880089/13673708/50906dae-e6a8-11e5-9cfd-96caeb3cdc9d.png)

**Comment by alex-wilmer** [comment]
Maybe it messed up because I called my Tutorial directory `enclave`? I briefly looked at the code in this repo last night, but I can look again when I get back from work.

**Comment by eanplatter** [comment]
Oh man look at that ASCII art! :smile: 

Yes, please check again, the reason it goes up is because it's running from the dependency not the root.

If anyone knows of a better way to find the right file path I am all ears.

**Comment by AgentEpsilon** [comment]
[According to this blog post](http://www.hacksparrow.com/understanding-directory-references-in-node-js.html), `__dirname` always points to the directory the script file resides in, while `process.cwd()` points to the directory the process was run inside of. ShellJS's `pwd()` just executes `path.resolve(process.cwd())`.

After _extensive testing_ (read: making a local module w/ a postinstall and `npm install`ing it) it appears that for enclave, `__dirname` will give the module directory + "/src/postinstall", while `process.cwd()` will give just the module directory (i.e. "/project/folder/node_modules/enclave"). Therefore, `path.join(process.cwd(), "../..")` should give the project root when called in the postinstall script.

**Comment by alex-wilmer** [comment]
So did anything need to be changed on my end / in the code?

**Comment by FiberJW** [comment]
Just don't name your folder the same as enclave. npm often can't tell the difference between the two

**Comment by AgentEpsilon** [comment]
I think I just figured it out actually. If you look in the screenshots, the install scripts are all running in /Users/azium/node_modules/. I'm willing to bet that folder existed before you installed, and since npm tries to walk upwards until it finds what it sees to be a project root, it installed it there. Kinda weird, though - @alex-wilmer, can you check if there is a `package.json` file in your home path? (`cd ~ && ls | grep "package.json"`)
