### ISSUE TITLE
Contributor Guide

### ISSUE THREAD

**Issue by FiberJW** [eanplatter/enclave#27]
It's really hard to tell how to run this when developing new features. I honestly have little to no idea and one other contributor had to accentuate an uncertainty because (from what i think) there's a lack of knowledge of how to test our features in development. How do you go about it @eanplatter ? It would help us all :+1:

**Comment by eanplatter** [comment]
It would be nice to have some more information about that.

Currently my workflow is pretty hacky, I am pretty much running things manually, like `node src/postinstall/index.js` and then seeing what it does. 

I've never written a library for creating new apps before, so it seems like it might be kind of weird to do things like have an example folder, what would even be in an example folder?

Perhaps creating a sort of, dev sandbox with some extra commands for quickly testing out pieces of the library.

I'll mull over this tonight and see what I can come up with.

**Comment by FiberJW** [comment]
Sweet! This will help the progress of this tool much smoother. I'm glad to be a part of it :smile:

**Comment by eanplatter** [comment]
@datwheat another thing I do, is install the project in a new app, and then work on it from the `node_modules` folder directly. Then when I'm done I copy/paste my changes to my project repo.

**Comment by FiberJW** [comment]
good idea!

**Comment by eanplatter** [comment]
Got a first draft up on master! Gonna close this issue for now.
