### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by FiberJW** [eanplatter/enclave#28]
How are you going about version scheming for enclave?

**Comment by eanplatter** [comment]
Currently I am just doing it manually, but we definitely want something more streamlined, we also probably want some CI stuff too, at least for doing things like linting PRs before we can merge them, and running tests (once we've got tests)

Any ideas on how you'd like to do versioning?

**Comment by FiberJW** [comment]
I don't know versioning well, But I was thinking we could lay out what features we are planning for different versions (timeline), and develop on release branches with feature branches stemming from that.

**Comment by FiberJW** [comment]
@eanplatter this explains it better: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by FiberJW** [comment]
Are you `npm version patch && npm publish`-ing each time you push to github? I'm just wondering how often the live module is updated on npm @eanplatter

**Comment by eanplatter** [comment]
I am doing it kind of at my own discretion, if it's an update that might not go to the npm module, like in the `examples` directory I might not. 

At my work we make a `CHANGELOG.md` file which tracks the updates. This might be a good thing to do moving forward. Here's an example: https://github.com/TechnologyAdvice/stardust/blob/master/CHANGELOG.md

**Comment by FiberJW** [comment]
That's a good idea! Also could you add me to the project as a contributor? @eanplatter

**Comment by FiberJW** [comment]
also are you going to remove the `enclave-cli` package on npm?

**Comment by eanplatter** [comment]
The `enclave-cli` isn't anything right now, but I've got some ideas on a different approach to enclave in a pure CLI format. So I might keep it around.

**Comment by eanplatter** [comment]
@datwheat Message me on twitter, about being added as a contributor. I think it sounds like a good idea.

**Comment by FiberJW** [comment]
Ah okay. I thought It was just a stray module you made when you were first creating the idea. And isn't it already pure CLI?

**Comment by eanplatter** [comment]
It kind of was :D

**Comment by eanplatter** [comment]
Gonna close this for now.
