### ISSUE TITLE
Install prompt prints default value twice

### ISSUE THREAD

**Issue by FiberJW** [eanplatter/enclave#33]
![Check this screenshot](https://cloud.githubusercontent.com/assets/12488826/13691374/54b7d706-e706-11e5-9a6c-0232a2379e07.png)

**Comment by FiberJW** [comment]
Other than that everything works. JSX, [S]CSS features work well.

**Comment by eanplatter** [comment]
Nice, I am glad those features work, I think I've almost got something cobbled together for running some manual tests, like an example app inside the repo you can run while developing.

Do you want to try and tackle this double prompt issue? @datwheat

**Comment by eanplatter** [comment]
I think I know the issue with the prompts, I believe the prompt library enclave is using automagically adds the default values like that, so if they were to be removed from the descriptions here: https://github.com/eanplatter/enclave/blob/master/src/postinstall/prompts.js they should go away.
