### ISSUE TITLE
Added fonts?

### ISSUE THREAD

**Issue by codetony25** [eanplatter/enclave#48]
I'm trying to import some .otf fonts in my sass files and it gives me this error:

ERROR in ../css-loader!../sass-loader!/Users/tonynguyen/Desktop/codetony/src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../../assets/fonts/BebasNeue.otf in /Users/tonynguyen/Desktop/codetony/src/styles
 @ ../css-loader!../sass-loader!/Users/tonynguyen/Desktop/codetony/src/styles/main.scss 6:19924-19967

I'm sure it's the correct path. however may I ask if we have this in the loader to support different types of font files?

**Comment by codetony25** [comment]
Oh, as I expected: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

So we don't have a loader that supports this just yet.

**Comment by eanplatter** [comment]
Yeah, I've never tried to load fonts with webpack before. Interesting problem. You can view the current loader config [here](https://github.com/eanplatter/enclave/blob/master/webpack.config.js#L56)

What loader do people normally use for otf files?

**Comment by goldensunliu** [comment]
@eanplatter use

```
{
          test: /\.(otf|eot|ttf|woff)/,
          loader: 'url-loader?limit=8192'
        }
```

**Comment by goldensunliu** [comment]
you don't have to process these files whats so ever, you just gotta load them via a simple url-loader

**Comment by eanplatter** [comment]
@goldensunliu or @tonytainguyen either of you interested in submitting a PR for this?

**Comment by eanplatter** [comment]
It looks good @goldensunliu

**Comment by goldensunliu** [comment]
@eanplatter https://github.com/eanplatter/enclave/pull/50
have a good weekend bro.

**Comment by eanplatter** [comment]
@goldensunliu is url-loader a dep we need to install?

**Comment by goldensunliu** [comment]
@eanplatter o yeah opps

**Comment by goldensunliu** [comment]
https://github.com/webpack/url-loader

**Comment by eanplatter** [comment]
Add it and I'll merge.

**Comment by goldensunliu** [comment]
@eanplatter done, I prefer locking in version when using package.json

**Comment by eanplatter** [comment]
:+1: sounds good, thanks @goldensunliu

**Comment by goldensunliu** [comment]
@eanplatter let me know how I can help. I will be watching :-D

**Comment by eanplatter** [comment]
Sounds good! Anything helps! Have a nice weekend!

**Comment by FiberJW** [comment]
Looks like there's gonna be a problem... 
![rp](https://cloud.githubusercontent.com/assets/12488826/13726693/79599a26-e8a1-11e5-8993-67d2cf6a123d.png)

**Comment by FiberJW** [comment]
When I npm install it doesn't install url-loader's dependency

**Comment by FiberJW** [comment]
This is easily fixed by adding file-loader to enclave's package.json
