### ISSUE TITLE
Request for server sider rendering

### ISSUE THREAD

**Issue by goldensunliu** [eanplatter/enclave#49]
Any plan on this?

**Comment by eanplatter** [comment]
I am woefully inexperienced with SSR, but I am interested to see what it would look like, any ideas on how we could implement it?

**Comment by goldensunliu** [comment]
gonna be some moving pieces:
- [ ] build a express server entry point for server side rendering
- [ ] inject css styles on render

to start. for more complicated cases, you also have to form opinion around how the dehydration and hydration of state is done from the server to client side.

some good examples include:
- https://github.com/kriasoft/react-starter-kit
- https://github.com/erikras/react-redux-universal-hot-example
- https://github.com/Driftt/web-base

**Comment by eanplatter** [comment]
Hi @goldensunliu I am going to close this issue. If you are interested in creating a PR for this I'd be interested in discussing it. A discussion around code is usually more productive than a discussion on an issue. :)

**Comment by goldensunliu** [comment]
agreed bro.
