### ISSUE TITLE
Make Babel presets / plugins and Webpack loaders configurable.

### ISSUE THREAD

**Issue by eanplatter** [eanplatter/enclave#68]
Right now Enclave is essentially highjacking the users control of webpack and babel in exchange for simplicity. That's the point.

But we don't necessarily want to eliminate all configuration.

I'd like to extend the basic configuration of webpack loaders and babel presets / plugins into the generation of the `enclave.js` file via the postinstall script.

This won't add any additional prompts to the user on install, but will export arrays of loaders, presets, and plugins. It will default to the loaders and plugins we're currently using, and any the user adds will be installed and added into the appropriate files.

Looks something like this:

``` js
/* enclave.js */
// ...
exports.loaders = ['json', 'url']
exports.presets = ['es2015', 'react']
// ...
```

If the user adds loaders or presets they will be integrated into enclave after they re run the npm start script.

Highjacking APIs is kind of a sensitive subject, because it makes it impossible for the user to reference the API docs of babel and webpack for help, which means enclave bears the brunt of it. But I think for now that's okay.

**Comment by FiberJW** [comment]
![9mVms6Z3p8VZC](https://camo.githubusercontent.com/9d24eec6d90fb8cba7e2d8c10186b7d1ab8e0d15/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f396d566d73365a337038565a432f67697068792e676966)
