### ISSUE TITLE
Explore auto-install features and other things that can make development more convenient.

### ISSUE THREAD

**Issue by eanplatter** [eanplatter/enclave#69]
I think this guy's auto dep install is kind of neat, might be an interesting feature to think about. 

EDIT: forgot the link :P
https://github.com/insin/nwb#auto-installing-npm-dependencies

**Comment by FiberJW** [comment]
By this guy he means https://github.com/insin/nwb#auto-installing-npm-dependencies

**Comment by mattmccray** [comment]
Or this: https://github.com/ericclemmons/npm-install-webpack-plugin

**Comment by FiberJW** [comment]
@mattmccray that plugin looks dank![dank-memes-xT0BKiaM2VGJ553P9K](https://camo.githubusercontent.com/cd3fe48b6742d6a40bdcb2a9b2165472d040a0cc/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f785430424b69614d3256474a35353350394b2f67697068792e676966)

**Comment by FiberJW** [comment]
I'll tackle a pr implementing the second plugin :+1:

**Comment by mattmccray** [comment]
@datwheat You know it! 

I've been meaning to hook up that plugin in my work project, excited to see what you think of it! (And to play with it within an enclave project)
