### ISSUE TITLE
Support for Routing?

### ISSUE THREAD

**Issue by emars** [eanplatter/enclave#76]
Whenever the reloader refreshes the page on a route other than index, I get an express route not found error.

This could be potentially solved by a catch all route that just serves the index?

**Comment by FiberJW** [comment]
This isn't an issue. It's just how routers work. Providing a catch all would defeat the purpose of there being routes at all and would limit other users from using their own routing solutions (React Router, etc). I'd just stay on the index. Unless there is an actual error that affects the app being served on the correct route, I think that this isn't a problem.
![rawr-AF3xMm5xbp8k0](https://camo.githubusercontent.com/6e1a9eafa19b7375ef088d2c713c843cb8910fb6/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f414633784d6d35786270386b302f67697068792e676966)

**Comment by FiberJW** [comment]
Is this a react router issue or something? Any questions?

**Comment by eanplatter** [comment]
I'd like to leave enclave out of handling more than webpack and babel setup.

But if you're using react router (or some other router) and you think enclave is breaking the router then we might have a problem.
