### ISSUE TITLE
Use babel 6

### ISSUE THREAD

**Issue by eanplatter** [eanplatter/enclave#8]
Currently I had the webpack config using babel 5 due to its simplicity, but users should be able to use babel 6  and it's configuration tools, like having a babelrc file.

**Comment by mcMickJuice** [comment]
do you want this to be an option when you first run enclave command or would you just upgrade enclave to use babel 6 going forward?

**Comment by eanplatter** [comment]
Babel was pretty adamant about transitioning, and was going to deprecate babel-5 rather quickly, so I'd say it would be best to just transition over to babel6.

One thing babel6 does bring is the `.babelrc` file with things like presets.

What I was thinking was to have the postinstall script create a `.babelrc` file in the users app, like it does with the `enclave.js` file, and then sets some babel preset defaults, like react presets, and stage1 presets.

We could also have enclave completely abstract out the babel interface, where you change any babel options in your `enclave.js` file. But the problem with this is that of babel changes anything with their API it might mess with our abstraction.

Thoughts?

**Comment by alex-wilmer** [comment]
I think generating a `.babelrc` file is the way to go. If users switch to another project without Enclave they can use your sensible defaults as an example.

**Comment by eanplatter** [comment]
How exactly does webpack interact with the `.babelrc` file? Does it just automatically search for it? if so our webpack abstraction might be looking at the enclave directory rather than the users directory. 

If we can tell webpack where to find it then that would be a sane approach, but if it does it automatically we might want a way to glean it from the user somehow.

**Comment by AgentEpsilon** [comment]
Considering enclave is supposed to be a quick setup for a react/es2015 webpack+babel setup, and both webpack and babel are completely contained within this package, wouldn't it make sense to just keep the babel config inside the package?

On a separate note, the .babelrc file actually isn't necessary - the information can be included under a "babel" object in the package.json, [or passed to the babel-loader as shown here](https://github.com/babel/babel-loader#options). One idea I had was to provide a default babel configuration in the package (`{presets:['es2015', 'react']}`), and make it overridable as an option in `enclave.js`.

**Comment by levithomason** [comment]
Webpack does not interact with `.babelrc`.  Babel does, so loaders that use babel will pickup on the `.babelrc`.  As @AgentEpsilon has said, you can also use package.json or a webpack loader query (inline or query object) to define babel config.

One primary difference to consider between `.babelrc` or a `package.json` babel config is that other tools running babel (or the user) will use the same babel config if it is in the rc or package key.  If it is buried in a webpack loader config, then only that loader will know what the config is.

I would think the config should be relevant to the whole project, so ruling out either one of the loader config options.  That leaves the rc or package.

I'm also like the package.json option for enclave as it simplifies the project and keeps everything together.  Plus, enclave is already writing to the `package.json` for the start script (though I don't think it should be writing to `start`, separate issue...).

**Comment by AgentEpsilon** [comment]
@levithomason The reason why setting the babel config as a webpack loader query is optimal to me is that it can be dynamically loaded from another file, in this case the enclave.js configuration file in the root project directory. Options are already provided in that file for various webpack settings, so I figured that allowing the user to override the babel-loader query would fall into that category.

**Comment by levithomason** [comment]
What is the advantage of dynamically loading babel config from enclave.js vs package.json or babelrc?

The downside is that putting it in an unconventional place like enclave.js means babel itself doesn't know where it is.  If it's package.json (or rc), babel knows where it is and it can still be dynamically loaded into  other files. 

Worth noting babel recommends using a babelrc.

Thoughts?

**Comment by AgentEpsilon** [comment]
I think you're misinterpreting. I'm suggesting we store our _default_ babel
config in enclave's webpack.config.js, and provide an _optional_ babel
config setting accessible in the user's enclave.js. That way if the user
wants to mess with the babel config, they don't have to completely
restructure their workflow.

That being said, the goal of this module is to handle all of that for you,
so it actually might be more in line to just shove the babel config into
the .babelrc. Adding it to package.json is functionally similar, but it
isn't as clear where the config is.

I vote for using `.babelrc`.

**Comment by levithomason** [comment]
:+1: sounds like a good first go to me. We can iterate after getting more use out of it. 

What do you say @eanplatter?

**Comment by eanplatter** [comment]
I like the idea of features being available but out of sight until needed. @AgentEpsilon  would you like to make a proposal PR for this?

**Comment by AgentEpsilon** [comment]
I'm on it!
